name: Publish Package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    if: github.repository == 'tinylibs/tinyspy'
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: Set node version to 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build
        run: pnpm build

      - name: Publish to npm
        run: npm i -g npm@^11.5.2 && pnpm clean-publish

      - name: Generate Changelog
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
